const data =[{"_id":"01GW1MD0QD4NNSP424XFEMFH28","title":"Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.","author":"lfarncombe0","url":"http://dummyimage.com/240x100.png/5fa2dd/ffffff","likes":1},
{"_id":"01GW1MD0QGJ3XMSVWJ7K2GSKNR","title":"Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.","author":"asnodin1","url":"http://dummyimage.com/218x100.png/ff4444/ffffff","likes":78},
{"_id":"01GW1MD0QKF9KKMMR2A6WJWB80","title":"Aliquam erat volutpat. In congue. Etiam justo.","author":"fjiruca2","url":"http://dummyimage.com/240x100.png/cc0000/ffffff","likes":42},
{"_id":"01GW1MD0QNMYAB05GGGRNJ2FWY","title":"Curabitur at ipsum ac tellus semper interdum.","author":"acregeen3","url":"http://dummyimage.com/110x100.png/ff4444/ffffff","likes":65},
{"_id":"01GW1MD0QQF4XRV2GMX8KWZYFJ","title":"Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.","author":"bkillgus4","url":"http://dummyimage.com/131x100.png/ff4444/ffffff","likes":87},
{"_id":"01GW1MD0QTF3KM0PPE1E2NY64H","title":"In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.","author":"ehandmore5","url":"http://dummyimage.com/183x100.png/dddddd/000000","likes":75},
{"_id":"01GW1MD0QYS6NMGTT0M06YW65T","title":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.","author":"wcripps6","url":"http://dummyimage.com/130x100.png/cc0000/ffffff","likes":4},
{"_id":"01GW1MD0R0M12R52DFBARPAS17","title":"Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.","author":"ddigwood7","url":"http://dummyimage.com/216x100.png/ff4444/ffffff","likes":61},
{"_id":"01GW1MD0R3CHR755SJPVXB9ABC","title":"Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.","author":"ziacovone8","url":"http://dummyimage.com/179x100.png/ff4444/ffffff","likes":24},
{"_id":"01GW1MD0R5SBB6BE4DSVE4S20V","title":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.","author":"klardge9","url":"http://dummyimage.com/200x100.png/cc0000/ffffff","likes":73}]

module.exports = data;